services:
    openldap:
        image: osixia/openldap:latest
        ports:
            - "389:389"
            - "636:636"
        env_file:
            - ./env/.env_ldap
        volumes:
            - /var/lib/ldap
            - /etc/ldap/slapd.d
            - /container/service/slapd/assets/certs/
         
    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        env_file:
            - ./env/.env_ldap
        ports:
            - "8081:80"
        depends_on:
            - openldap
    
    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./gitlab/config:/etc/gitlab
            - ./gitlab/logs:/var/log/gitlab
            - ./gitlab/data:/var/opt/gitlab
        env_file:
            - ./env/.env_gitlab
        restart: always
        depends_on:
            - openldap
    
    mongodb:
        image: docker.io/bitnamilegacy/mongodb:latest
        volumes:
            -  ./mongodb_data:/bitnami/mongodb
        env_file:
            - ./env/.env_rocketchat

    rocketchat:
        image: rocketchat/rocket.chat:latest
        container_name: rocketchat
        ports:
            - "3000:3000"
        env_file:
            - ./env/.env_rocketchat
        depends_on:
            - mongodb